[hosts]
dev.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[nas_access]
dev.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[devops]
dev.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[docker]
dev.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[tailscale]
dev.home.ptre.es

[k8s]
