[hosts]
elmo.home.ptre.es
kermit.home.ptre.es

dev.home.ptre.es
k8s1.home.ptre.es
k8s2.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
# services.home.ptre.es

[vms]
dev.home.ptre.es
k8s1.home.ptre.es
k8s2.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es

[nas_access]
dev.home.ptre.es
k8s1.home.ptre.es
k8s2.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
# services.home.ptre.es

[devops]
dev.home.ptre.es
k8s1.home.ptre.es
k8s2.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
# services.home.ptre.es

[docker]
dev.home.ptre.es
plex.home.ptre.es
privacy.home.ptre.es
# services.home.ptre.es

[tailscale]
dev.home.ptre.es

[microk8s]
k8s1.home.ptre.es
k8s2.home.ptre.es

[proxmox]
elmo.home.ptre.es
kermit.home.ptre.es