[hosts]
wsl                     ansible_connection=local
k1.home.ptre.es
k2.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[devops]
wsl
k1.home.ptre.es
k2.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[docker]
wsl
privacy.home.ptre.es
services.home.ptre.es
