[hosts]
wsl                     ansible_connection=local
privacy.home.ptre.es
services.home.ptre.es

[devops]
wsl
privacy.home.ptre.es
services.home.ptre.es

[docker]
wsl
privacy.home.ptre.es
services.home.ptre.es