[hosts]
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[devops]
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[docker]
plex.home.ptre.es
privacy.home.ptre.es
services.home.ptre.es

[k8s]
