collections:
  - community.docker
  - community.general
roles:
  - src: git+https://github.com/homeopz/ansible-role-apt.git
    name: apt
    version: main
  - src: git+https://github.com/homeopz/ansible-role-docker.git
    name: docker
    version: main
  - src: git+https://github.com/homeopz/ansible-role-nfs.git
    name: nfs
    version: main    
  - src: git+https://github.com/homeopz/ansible-role-users.git
    name: users
    version: main    