---

- name: Setup host
  hosts: vms
  become: true
  tasks:
    - ansible.builtin.hostname:
        name: "{{ ansible_host }}"
        use: systemd
  tags: [hostname]

- name: Upgrade packages
  hosts: hosts
  become: true
  roles:
    - role: apt
      vars:
        apt_update: true
        apt_upgrade: true
        apt_autoremove: true
  tags: [apt-install]

- name: Update packages
  hosts: hosts
  become: true
  roles:
    - role: apt
      vars:
        apt_update: true
        apt_upgrade: true
        apt_autoremove: true
  tags: [apt-update, apt-upgrade, apt-autoremove]

- name: Install Baseline packages
  hosts: hosts
  become: true
  roles:
    - role: apt
      vars:
        apt_install: "{{ apt_packages_baseline }}"
  tags: [apt-install, baseline]
    
- name: Setup users
  hosts: hosts
  become: true
  roles:
    - role: users
  tags: [users]

- name: Setup NFS access to Home NAS
  hosts: nas_access
  become: true
  tags: [nfs, nas]
  roles:
    - role: nfs