---
- name: Upgrade packages
  hosts: hosts
  become: true
  roles:
    - role: apt
      vars:
        apt_update: true
        apt_upgrade: true
        apt_autoremove: true
  tags:
    - apt
    - upgrade

---
- name: Update packages
  hosts: hosts
  become: true
  tags: [apt, update, upgrade, autoremove]
  roles:
    - role: apt
      vars:
        apt_update: true
        apt_upgrade: true
        apt_clean: true
        apt_autoremove: true

- name: Install Baseline packages
  hosts: hosts
  become: true
  tags: [apt, install, baseline]
  roles:
    - role: apt
      vars:
        apt_install: "{{ apt_packages_baseline }}"
  tags:
    - apt
    - install
    - common

- name: Install DevOps packages
  hosts: devops
  become: true
  tags: [apt, install, devops]
  roles:
    - role: apt
      vars:
        apt_install: "{{ apt_packages_devops }}"
  tags:
    - apt
    - install
    - devops

- name: Setup users
  hosts: hosts
  become: true
  roles:
    - role: users
  tags:
    - users

- name: Install DevOps tooling
  hosts: devops
  become: true
  tags: [install, devops, tools]
  roles:
    - role: tools-devops
      vars:
        ansible_install: true
        helm_install: true
        kubectl_install: true
        terraform_install: true

- name: Setup users
  hosts: hosts
  become: true
  tags: [users]
  roles:
    - role: users
  ignore_errors: true

- name: Setup NFS
  hosts: hosts
  become: true
  tags: [nfs]
  roles:
    - role: nfs

- name: Install Docker
  hosts: docker
  become: true
  tags: [docker, compose]
  roles:
    - role: docker
<<<<<<< HEAD
  tags:
    - docker

- name: Install DevOps tooling
  hosts: devops
  become: true
  roles:
    - role: tools-devops
      vars:
        ansible_install: true
        helm_install: true
        kubectl_install: true
        terraform_install: true
  tags:
    - devops
    - tools
    - install
=======

- name: Install MicroK8S
  hosts: k8s
  become: true
  tags: [k8s, microk8s]
  roles:
    - role: microk8s
>>>>>>> e9fca13d2b2cfab354db377a133d7e7a8d444572
