
- name: Install common packages
  hosts: hosts
  become: true
  roles:
    - role: apt
      vars:
        apt_install: "{{ apt_packages_baseline }}"

- name: Install DevOps packages
  hosts: devops
  become: true
  roles:
    - role: apt
      vars:
        apt_install: "{{ apt_packages_devops }}"

- name: Install Docker
  hosts: docker
  become: true
  roles:
    - role: docker
  tags:
    - docker